# Container base image
FROM ubuntu:latest

# Update APT using apt-get update
RUN apt-get update

# Upgrade currently installed software through APT using apt-get upgrade -y
RUN apt-get upgrade -y

# Echo “Hello, World!” on the terminal.
CMD [ "echo", "Hello, World!" ]
